version: 0.0
os: linux 
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root
